import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import Head from "next/head";
import "./globals.css";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={raleway.className}>{children}</body>
    </html>
  );
}
